title: "武振建 | Zhenjian Wu"
description: "中文为主、支持中英文切换的学术主页"
baseurl: ""
url: "https://wuzhenjian0125.github.io"
lang: zh-CN
timezone: Asia/Shanghai
markdown: kramdown
permalink: pretty

collections:
  publications:
    output: false
  projects:
    output: false
